export const surpriseMePrompts = [
    "A purple cat with butterfly wings",
    "A skyscraper made of candy",
    "A bicycle floating in space",
    "A tree made of books",
    "A flamingo wearing a top hat",
    "A robot playing chess with a human",
    "A castle made of clouds",
    "A waterfall flowing upwards",
    "A flying car powered by balloons",
    "A jellyfish with a rainbow pattern",
    "A mountain range made of ice cream",
    "A cityscape underwater",
    "A fox wearing sunglasses",
    "A teapot made of chocolate",
    "A robot painting a masterpiece",
    "A turtle riding a skateboard",
    "A banana playing the piano",
    "A house made of playing cards",
    "A rainbow-colored zebra",
    "A flower bouquet made of feathers",
    "A lion wearing a crown",
    "A pizza with legs",
    "A robot serving ice cream",
    "A squirrel riding a bicycle",
    "A dolphin flying through the sky",
    "A castle made of sand",
    "A cat wearing a spacesuit",
    "A tree with rainbow-colored leaves",
    "A robot playing soccer",
    "A flamingo surfing on a wave",
    "A waterfall made of fire",
    "A floating island in the clouds",
    "A penguin riding a unicycle",
    "A hot air balloon in the shape of a teapot",
    "A robot dancing ballet",
    "A turtle wearing a top hat",
    "A bird made of flowers",
    "A lion riding a skateboard",
    "A house with legs walking in a city",
    "A rainbow-colored butterfly",
    "A cat playing a musical instrument",
    "A tree with roots made of spaghetti",
    "A robot climbing a mountain",
    "A shark wearing a suit",
    "A waterfall flowing with chocolate",
    "A floating city in the sky",
    "A monkey riding a bicycle",
    "A cupcake with wings",
    "A robot juggling",
    "A turtle playing basketball",
    "A banana reading a book",
    "A house made of clouds",
    "A rainbow-colored elephant",
    "A cat wearing a crown",
    "A tree made of candy",
    "A robot playing the guitar",
    "A dolphin wearing a hat",
    "A castle made of ice",
    "A flamingo riding a bicycle",
    "A waterfall made of candy",
    "A floating island with trees made of fire",
    "A penguin playing tennis",
    "A hot air balloon in the shape of a pizza",
    "A robot painting graffiti",
    "A turtle wearing sunglasses",
    "A bird made of ice cream",
    "A lion flying in a spaceship",
    "A house with wheels driving on a rainbow",
    "A rainbow-colored snake",
    "A cat playing basketball",
    "A tree with roots made of books",
    "A robot skiing down a mountain",
    "A shark wearing sunglasses",
    "A waterfall flowing with ice cream",
    "A floating city underwater",
    "A monkey wearing a top hat",
    "A cupcake playing the piano",
    "A turtle riding a rocket",
    "A banana riding a skateboard",
    "A house made of chocolate",
    "A rainbow-colored giraffe",
    "A cat playing chess",
    "A tree made of feathers",
    "A robot surfing on a wave",
    "A dolphin wearing sunglasses",
    "A castle made of clouds",
    "A flamingo playing soccer",
    "A waterfall made of flowers",
    "A floating island with trees made of candy",
    "A penguin wearing a bowtie",
    "A hot air balloon in the shape of a burger",
    "A robot breakdancing",
    "A turtle wearing a crown",
    "A bird made of chocolate",
    "A lion riding a roller coaster",
    "A house floating in space",
    "A rainbow-colored octopus",
    "A cat playing the guitar",
    "A tree with roots made of feathers",
    "A robot climbing a skyscraper",
    "A shark playing the drums",
    "A waterfall flowing with rainbow-colored paint",
    "A floating city on the moon",
    "A monkey wearing sunglasses",
    "A cupcake playing basketball",
    "A turtle riding a dinosaur",
    "A banana playing soccer",
    "A house made of ice cream",
    "A rainbow-colored butterfly",
    "A cat wearing roller skates",
    "A tree made of balloons",
    "A robot playing the violin",
    "A dolphin wearing a bowtie",
    "A castle made of sand",
    "A flamingo riding a roller coaster",
    "A waterfall made of fireflies",
    "A floating island with trees made of books",
    "A penguin wearing a top hat",
    "A hot air balloon in the shape of an apple",
    "A robot playing the trumpet",
    "A turtle wearing sunglasses",
    "A bird made of candy",
    "A lion flying with wings",
    "A house with legs walking on a rainbow",
    "A rainbow-colored tiger",
    "A cat playing the drums",
    "A tree with roots made of spaghetti",
    "A robot skiing on a rainbow",
    "A shark wearing a crown",
    "A waterfall flowing with chocolate syrup",
    "A floating city in the desert",
    "A monkey riding a rocket",
    "A cupcake playing the saxophone",
    "A turtle playing the guitar",
    "A banana wearing sunglasses",
    "A house made of clouds",
    "A rainbow-colored elephant",
    "A cat playing tennis",
    "A tree made of candy canes",
    "A robot breakdancing on the moon",
    "A dolphin wearing roller skates",
    "A castle made of ice cream",
    "A flamingo playing the saxophone",
    "A waterfall made of cotton candy",
    "A floating island with trees made of ice",
    "A penguin wearing a crown",
    "A hot air balloon in the shape of a cupcake",
    "A robot playing basketball",
    "A turtle riding a rainbow",
    "A bird made of books",
    "A lion wearing roller skates",
    "A house floating in a cloud",
    "A rainbow-colored snake",
    "A cat playing the violin",
    "A tree with roots made of chocolate",
    "A robot climbing a volcano",
    "A shark playing basketball",
    "A waterfall flowing with lemonade",
    "A floating city in the jungle",
    "A monkey wearing roller skates",
    "A cupcake playing the drums",
    "A turtle wearing a bowtie",
    "A banana riding a roller coaster",
    "A house made of flowers",
    "A rainbow-colored giraffe",
    "A cat wearing a hat",
    "A tree made of ice",
    "A robot surfing on a rainbow",
    "A dolphin wearing rollerblades",
    "A castle made of candy",
    "A flamingo riding a skateboard",
    "A waterfall made of chocolate",
    "A floating island with trees made of clouds",
    "A penguin playing the guitar",
    "A hot air balloon in the shape of a donut",
    "A robot painting a sunset",
    "A turtle playing the drums",
    "A bird made of ice",
    "A lion flying with a jetpack",
    "A house with wheels driving on a rainbow",
    "A rainbow-colored horse",
    "A cat playing basketball",
    "A tree with roots made of feathers",
    "A robot skiing on a mountain",
    "A shark wearing sunglasses",
    "A waterfall flowing with ice cream",
    "A floating city underwater",
    "A monkey wearing a top hat",
    "A cupcake playing the piano",
    "A turtle riding a rocket",
    "A banana riding a skateboard",
    "A house made of chocolate",
    "A rainbow-colored giraffe",
    "A cat playing chess",
    "A tree made of feathers",
    "A robot surfing on a wave",
    "A dolphin wearing sunglasses",
    "A castle made of clouds",
    "A flamingo playing soccer",
    'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
]
